### PR TITLE
submit

### PR DESCRIPTION
**Pull request by HridyeshKumar**

### CODE REVIEW

**Comment by madhurimarawat** [comment]
Thank you for your pull request! I appreciate your contribution to the repository. However, I noticed that the description for the request is quite brief, with just the word "submit." To help me better understand the changes and review them efficiently, could you please provide a more detailed description of what your pull request entails? This will ensure that I can assess it thoroughly and integrate it smoothly. Thank you again for your effort and collaboration!

**Comment by HridyeshKumar** [comment]
2023 ka pyqs hai

**Comment by madhurimarawat** [comment]
To proceed with merging the pull request and updating the documentation, could you please specify the folder and file you have added? This will help ensure the README and documentation are accurately updated.

**Comment by madhurimarawat** [comment]
I have added detailed documentation in the [CONTRIBUTING.md](https://github.com/madhurimarawat/Semester-Notes/blob/main/CONTRIBUTING.md) file on how to properly add changes and write a detailed pull request. Please review it for guidance on future contributions.

Additionally, please refer to the [pull request template](https://github.com/madhurimarawat/Semester-Notes/blob/main/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md) before creating a pull request to ensure that all necessary information is included for a smoother review process.

Since I haven't received a response for over a month, I am closing this pull request. Feel free to open it at any time with the updated changes and a detailed pull request description.

Thank you again for your effort and collaboration! 🚀

**Pull request closed without merging**
